language: c++

matrix:
  include:

    # Ubuntu - DEBUG
    - os: linux
      compiler: gcc
      dist: bionic
      env:
        - BUILD_TYPE=Debug
      script: &linux_script
        - |
          set -e
          mkdir -p libdash/cmake-build-${BUILD_TYPE}
          cd libdash/cmake-build-${BUILD_TYPE}

          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
          cmake --build . --target all

          export LD_LIBRARY_PATH=$(pwd)/bin
          ./bin/libdash_networkpart_test
    - os: linux
      compiler: gcc
      dist: xenial
      env:
        - BUILD_TYPE=Debug
      script: *linux_script
    - os: linux
      compiler: clang
      dist: bionic
      env:
        - BUILD_TYPE=Debug
      script: *linux_script
    - os: linux
      compiler: clang
      dist: xenial
      env:
        - BUILD_TYPE=Debug
      script: *linux_script

    # Ubuntu - RELEASE
    - os: linux
      compiler: gcc
      dist: bionic
      env:
        - BUILD_TYPE=Release
      script: *linux_script
    - os: linux
      compiler: gcc
      dist: xenial
      env:
        - BUILD_TYPE=Release
      script: *linux_script
    - os: linux
      compiler: clang
      dist: bionic
      env:
        - BUILD_TYPE=Release
      script: *linux_script
    - os: linux
      compiler: clang
      dist: xenial
      env:
        - BUILD_TYPE=Release
      script: *linux_script

    # OSX
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - BUILD_TYPE=Debug
      script: &osx_script
        - |
          mkdir -p libdash/cmake-build-${BUILD_TYPE}
          cd libdash/cmake-build-${BUILD_TYPE}

          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
          cmake --build . --target all

          ./bin/libdash_networkpart_test
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - BUILD_TYPE=Release
      script: *osx_script

    # Windows
    - os: windows
      language: shell
      env:
        - BUILD_TYPE=Debug
      script: &windows_script
        - |
          set -e
          mkdir -p libdash/cmake-build-${BUILD_TYPE}
          cd libdash/cmake-build-${BUILD_TYPE}

          cmake ..
          cmake --build . --config ${BUILD_TYPE}

          ./bin/${BUILD_TYPE}/libdash_networkpart_test.exe
    - os: windows
      language: shell
      env:
        - BUILD_TYPE=Release
      script: *windows_script

script:
  - echo "DONE."
